{% set name = "niondata" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0401144b2e8f68c31efd09163e8a66ecb2031761d3c3fc096a8b6453561ae783

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - nionutils >=0.4.0,<0.5.0
    - scipy
    - numpy >=1.21,<2.0

test:
  imports:
    - nion.data
    - nion.data.test

about:
  home: https://github.com/nion-software/niondata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A data processing library for Nion Swift.
  dev_url: https://github.com/nion-software/niondata

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
