{% set python_min = "3.11" %}
{% set name = "niondata" %}
{% set version = "15.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33a44b55caec168ad209ea43395e3a74f63c2eb17945f86ae7ff2aab8b6317f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - nionutils >=4.14,<5.0
    - numpy >=2.0,<3.0
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.data
    - nion.data.test

about:
  home: https://github.com/nion-software/niondata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A data processing library for Nion Swift.
  dev_url: https://github.com/nion-software/niondata

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
