{% set name = "niondata" %}
{% set version = "15.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 401c0be57505a82cc8df5a73521a4f3b39fc1d15effd5853af81761b277c0949

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - nionutils >=0.4.5,<5.0.0
    - scipy
    - numpy >=1.21,<2.0

test:
  imports:
    - nion.data
    - nion.data.test

about:
  home: https://github.com/nion-software/niondata
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A data processing library for Nion Swift.
  dev_url: https://github.com/nion-software/niondata

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
